version: '3.8'
services:
  mysql:
    container_name: trabalho-faculdade-sql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ncshop
      MYSQL_USER: user
      MYSQL_PASSWORD: 1777
    ports:
      - "3309:3306"