spring:
  datasource:
    url: jdbc:mysql://localhost:3309/ncshop
    username: user
    password: 1777
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
